### ISSUE TITLE
Convert `Update Available Course List` to a celery task

### ISSUE THREAD

**Issue by brutal-chaos** [orvsd/orvsd_central#101]
This should be an asynchronous task that doesn't require the user to wait.

**Comment by brutal-chaos** [comment]
Should this be a celery task? Yes it takes a bit of time, though we do not have a mechanism for alerting the user once it is done

**Comment by Kennric** [comment]
Since this is an interactive task, I don't think it belongs in celery.  I think the use case here is that an admin, after adding new course files, will want to make sure they are available in OC. A celery task running via cron could automate this, but I suspect someone will want to interactively insure that courses are added.

**Comment by brutal-chaos** [comment]
Closing since we are not turning this into a celery task.
